# PFE Master ESB

# Banking Customer Churn Prediction

## Notebook 01 — Data Inventory

### Objective

The objective of this notebook is to perform a complete inventory of all datasets used in the Banking Customer Churn Prediction project.

This notebook will:

- Load every dataset.
- Verify file accessibility.
- Analyse dataset dimensions.
- Identify columns.
- Understand the structure of each table.

No preprocessing, cleaning or Machine Learning will be performed in this notebook.

In [35]:
# ==========================================================
# IMPORT LIBRARIES
# ==========================================================

from pathlib import Path
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 120)

print("=" * 60)
print("PFE ESB - Banking Churn Prediction")
print("=" * 60)
print("Pandas :", pd.__version__)
print("NumPy  :", np.__version__)

============================================================
PFE ESB - Banking Churn Prediction
============================================================
Pandas : 3.0.5
NumPy  : 2.4.6

In [36]:
# ==========================================================
# PROJECT PATHS
# ==========================================================

PROJECT_ROOT = Path.cwd().parent

RAW_DATA = PROJECT_ROOT / "data" / "raw"
REFERENCE_DATA = PROJECT_ROOT / "data" / "reference"

OUTPUT_TABLES = PROJECT_ROOT / "outputs" / "tables"

OUTPUT_TABLES.mkdir(parents=True, exist_ok=True)

print("Project root :", PROJECT_ROOT)
print("Raw data     :", RAW_DATA)
print("Reference    :", REFERENCE_DATA)
print("Outputs      :", OUTPUT_TABLES)

Project root : c:\Users\Sarra\OneDrive\Desktop\PFE_CHURN_ESB
Raw data     : c:\Users\Sarra\OneDrive\Desktop\PFE_CHURN_ESB\data\raw
Reference    : c:\Users\Sarra\OneDrive\Desktop\PFE_CHURN_ESB\data\reference
Outputs      : c:\Users\Sarra\OneDrive\Desktop\PFE_CHURN_ESB\outputs\tables

In [37]:
# ==========================================================
# VERIFY AVAILABLE FILES
# ==========================================================

raw_files = sorted(RAW_DATA.glob("*"))
reference_files = sorted(REFERENCE_DATA.glob("*"))

print("=" * 60)
print("RAW DATA FILES")
print("=" * 60)

for file_path in raw_files:
    print(f"- {file_path.name}")

print("\n" + "=" * 60)
print("REFERENCE DATA FILES")
print("=" * 60)

for file_path in reference_files:
    print(f"- {file_path.name}")

============================================================
RAW DATA FILES
============================================================
- ATB_ACCOUNTS (1).xlsx
- DATA (1).csv
- JM.xlsx

============================================================
REFERENCE DATA FILES
============================================================
- dim_CATEGORY.ACCOUNT.xlsx
- dim_Closure_reason.xlsx
- dim_CURRENCY.xlsx
- dim_DAO.xlsx
- dim_INDUSTRY.xlsx
- dim_TARGET.xlsx
- dim_TRANSACTION.xlsx

In [38]:
# ==========================================================
# GENERIC DATA LOADER
# ==========================================================

def load_dataset(file_path: Path) -> pd.DataFrame:
    """
    Load a CSV or Excel dataset.

    CSV files in this project use ';' as separator.
    Excel files are loaded from their first worksheet.

    Parameters
    ----------
    file_path : Path
        Path of the dataset.

    Returns
    -------
    pd.DataFrame
        Loaded dataset.
    """

    extension = file_path.suffix.lower()

    if extension == ".csv":
        try:
            return pd.read_csv(
                file_path,
                sep=";",
                encoding="utf-8",
                low_memory=False
            )
        except UnicodeDecodeError:
            return pd.read_csv(
                file_path,
                sep=";",
                encoding="latin1",
                low_memory=False
            )

    if extension in [".xlsx", ".xls"]:
        return pd.read_excel(file_path)

    raise ValueError(f"Unsupported file format: {extension}")

In [39]:
# ==========================================================
# LOAD ALL DATASETS
# ==========================================================

datasets = {}

all_files = raw_files + reference_files

for file_path in all_files:
    print(f"Loading: {file_path.name}")

    datasets[file_path.name] = load_dataset(file_path)

print("\n" + "=" * 60)
print("All datasets successfully loaded.")
print("=" * 60)

Loading: ATB_ACCOUNTS (1).xlsx
Loading: DATA (1).csv
Loading: JM.xlsx
Loading: dim_CATEGORY.ACCOUNT.xlsx
Loading: dim_Closure_reason.xlsx
Loading: dim_CURRENCY.xlsx
Loading: dim_DAO.xlsx
Loading: dim_INDUSTRY.xlsx
Loading: dim_TARGET.xlsx
Loading: dim_TRANSACTION.xlsx

============================================================
All datasets successfully loaded.
============================================================

In [40]:
# ==========================================================
# DATASET INVENTORY
# ==========================================================

inventory = []

for name, dataframe in datasets.items():

    inventory.append({
        "Dataset": name,
        "Rows": dataframe.shape[0],
        "Columns": dataframe.shape[1],
        "Missing Values": int(dataframe.isna().sum().sum()),
        "Duplicate Rows": int(dataframe.duplicated().sum())
    })

inventory_df = pd.DataFrame(inventory)

display(inventory_df)

                     Dataset    Rows  Columns  Missing Values  Duplicate Rows
0      ATB_ACCOUNTS (1).xlsx  108599        7             685               0
1               DATA (1).csv  528884       34         5124580           38640
2                    JM.xlsx  537936       10         1032241           49920
3  dim_CATEGORY.ACCOUNT.xlsx      50        3               0               0
4    dim_Closure_reason.xlsx      32        2               0               0
5          dim_CURRENCY.xlsx      22        4               0               0
6               dim_DAO.xlsx     150        4               0               0
7          dim_INDUSTRY.xlsx     663        2               0               0
8            dim_TARGET.xlsx      11        2               0               0
9       dim_TRANSACTION.xlsx    3038        2               0               0

In [41]:
# ==========================================================
# CHECK MAIN DATASET
# ==========================================================

df_data = datasets["DATA (1).csv"]

print("Shape:", df_data.shape)
print("\nColumns:")
print(df_data.columns.tolist())

display(df_data.head())

Shape: (528884, 34)

Columns:
['CUSTOMER_NO', 'ACCOUNT_NO', 'NATIONALITY', 'RESIDENCE', 'MARITAL_STATUS', 'CUST_OPENING_DATE', 'DATE_OF_BIRTH', 'NATURE_CLIENT', 'BRANCH', 'SCORE_KYC', 'COMPLETED_FILE', 'LAST_REVIEW_DATE', 'NEXT__REVIEW_DATE', 'ACCOUNT_STATUS', 'ACCT_OPENING_DATE', 'ACCOUNT_CATEGORY', 'ACCOUNT_TYPE_DESC', 'CURRENCY', 'ACCT_CLOSE_DATE', 'CLOSURE_REASON', 'ACCT_BALANCE', 'INDUSTRY', 'SALARY', 'PRODUCT_GROUP', 'PRODUCT_LINE', 'PRODUCT', 'ACCOUNTNATURE', 'STARTDATE', 'MATURITYDATE', 'AMOUNT', 'FIXEDRATE', 'PRODUCT_STATUS', 'PARTYCLASS', 'LOB']

,CUSTOMER_NO,ACCOUNT_NO,NATIONALITY,RESIDENCE,MARITAL_STATUS,CUST_OPENING_DATE,DATE_OF_BIRTH,NATURE_CLIENT,BRANCH,SCORE_KYC,COMPLETED_FILE,LAST_REVIEW_DATE,NEXT__REVIEW_DATE,ACCOUNT_STATUS,ACCT_OPENING_DATE,ACCOUNT_CATEGORY,ACCOUNT_TYPE_DESC,CURRENCY,ACCT_CLOSE_DATE,CLOSURE_REASON,ACCT_BALANCE,INDUSTRY,SALARY,PRODUCT_GROUP,PRODUCT_LINE,PRODUCT,ACCOUNTNATURE,STARTDATE,MATURITYDATE,AMOUNT,FIXEDRATE,PRODUCT_STATUS,PARTYCLASS,LOB
0,113772024,2.012013e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20190827.0,3023.0,Crédit acquisition logement TEGF6,TND,20260128.0,NaN,-10714.347,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.527,Crédit acquisition logement TEGF6,1251227.0,1290627.0,10954600.0,4.5,CURRENT,Retail,4
1,113772022,2.012119e+09,TN,TN,M,20040930.0,19600923.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20260105.0,3611.0,DEPOTS A TERME,TND,20250630.0,NaN,0.000,9000,3300.537,ATB.PLACEMENT.NEG,DEPOSITS,ATB.CAT.NEG.SIM,DEPOTS A TERME,20260102.0,NaN,NaN,NaN,UNAUTH,Retail,4
2,113772024,2.011691e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20230612.0,3017.0,Crédit rénovation,TND,20260128.0,NaN,-113033.101,9000,2725.739,RT.CRD.IMMOBILERS,LENDING,RT.RT.CRD.IMMOBILERS.548,Crédit rénovation,1251227.0,1380527.0,113593077.0,4.5,CURRENT,Retail,4
3,113772024,2.010055e+09,TN,TN,M,20040930.0,19690529.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20220527.0,1011.0,Compte Allocation Touristique TND,TND,20260128.0,NaN,0.000,9000,2725.739,ATB.GRP.CUR.ACCT,ACCOUNTS,ATB.CUR.ACCT.ALL.TOURS.CARTE,Compte Allocation Touristique TND,NaN,NaN,0.0,NaN,NaN,Retail,4
4,113772022,2.011092e+09,TN,TN,M,20040930.0,19600923.0,PPH,5820,LR,YES,20250905.0,20290905.0,Closed,20250702.0,3611.0,DEPOTS A TERME,TND,20250630.0,NaN,0.000,9000,3300.537,NaN,NaN,NaN,DEPOTS A TERME,NaN,NaN,NaN,NaN,NaN,Retail,4

In [42]:
# ==========================================================
# SAVE INVENTORY
# ==========================================================

inventory_output = OUTPUT_TABLES / "01_dataset_inventory.xlsx"

inventory_df.to_excel(
    inventory_output,
    index=False
)

print("Inventory saved to:")
print(inventory_output)

Inventory saved to:
c:\Users\Sarra\OneDrive\Desktop\PFE_CHURN_ESB\outputs\tables\01_dataset_inventory.xlsx

In [45]:
# ==========================================================
# DATA DICTIONARY
# ==========================================================

data_dictionary = pd.DataFrame({

    "Column": df_data.columns,

    "Data Type": df_data.dtypes.astype(str),

    "Non Missing Values": df_data.notna().sum().values,

    "Missing Values": df_data.isna().sum().values,

    "Missing (%)":
        (df_data.isna().mean()*100).round(2).values,

    "Unique Values":
        df_data.nunique(dropna=True).values

})

display(data_dictionary)

,Column,Data Type,Non Missing Values,Missing Values,Missing (%),Unique Values
CUSTOMER_NO,CUSTOMER_NO,int64,528884,0,0.00,363569
ACCOUNT_NO,ACCOUNT_NO,float64,484444,44440,8.40,410587
NATIONALITY,NATIONALITY,str,528884,0,0.00,141
RESIDENCE,RESIDENCE,str,528884,0,0.00,137
MARITAL_STATUS,MARITAL_STATUS,str,410186,118698,22.44,4
CUST_OPENING_DATE,CUST_OPENING_DATE,float64,515262,13622,2.58,5352
DATE_OF_BIRTH,DATE_OF_BIRTH,float64,427569,101315,19.16,32002
NATURE_CLIENT,NATURE_CLIENT,str,528806,78,0.01,9
BRANCH,BRANCH,int64,528884,0,0.00,142
SCORE_KYC,SCORE_KYC,str,528039,845,0.16,5
COMPLETED_FILE,COMPLETED_FILE,str,289240,239644,45.31,1
LAST_REVIEW_DATE,LAST_REVIEW_DATE,float64,501479,27405,5.18,5006
NEXT__REVIEW_DATE,NEXT__REVIEW_DATE,float64,504302,24582,4.65,6795
ACCOUNT_STATUS,ACCOUNT_STATUS,str,484444,44440,8.40,2
ACCT_OPENING_DATE,ACCT_OPENING_DATE,float64,383959,144925,27.40,10103
ACCOUNT_CATEGORY,ACCOUNT_CATEGORY,float64,383959,144925,27.40,149
ACCOUNT_TYPE_DESC,ACCOUNT_TYPE_DESC,str,383959,144925,27.40,149
CURRENCY,CURRENCY,str,383959,144925,27.40,19
ACCT_CLOSE_DATE,ACCT_CLOSE_DATE,float64,221942,306942,58.04,646
CLOSURE_REASON,CLOSURE_REASON,str,143556,385328,72.86,18
ACCT_BALANCE,ACCT_BALANCE,float64,383959,144925,27.40,200311
INDUSTRY,INDUSTRY,int64,528884,0,0.00,644
SALARY,SALARY,float64,202235,326649,61.76,6011
PRODUCT_GROUP,PRODUCT_GROUP,str,320038,208846,39.49,33
PRODUCT_LINE,PRODUCT_LINE,str,320038,208846,39.49,4
PRODUCT,PRODUCT,str,320038,208846,39.49,225
ACCOUNTNATURE,ACCOUNTNATURE,str,383959,144925,27.40,149
STARTDATE,STARTDATE,float64,92728,436156,82.47,722
MATURITYDATE,MATURITYDATE,float64,79551,449333,84.96,4682
AMOUNT,AMOUNT,float64,305364,223520,42.26,178497
FIXEDRATE,FIXEDRATE,float64,79549,449335,84.96,722
PRODUCT_STATUS,PRODUCT_STATUS,str,92724,436160,82.47,7
PARTYCLASS,PARTYCLASS,str,528884,0,0.00,5
LOB,LOB,int64,528884,0,0.00,9

In [46]:
# ==========================================================
# SAVE DATA DICTIONARY
# ==========================================================

data_dictionary.to_excel(

    OUTPUT_TABLES /

    "02_DATA_Dictionary.xlsx",

    index=False

)

print("DATA Dictionary exported successfully.")

DATA Dictionary exported successfully.

In [47]:
# ==========================================================
# GENERAL INFORMATION
# ==========================================================

print("="*60)

print("DATASET INFORMATION")

print("="*60)

print(f"Rows    : {df_data.shape[0]:,}")

print(f"Columns : {df_data.shape[1]}")

print()

print(df_data.info())

============================================================
DATASET INFORMATION
============================================================
Rows    : 528,884
Columns : 34

<class 'pandas.DataFrame'>
RangeIndex: 528884 entries, 0 to 528883
Data columns (total 34 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CUSTOMER_NO        528884 non-null  int64
 1   ACCOUNT_NO         484444 non-null  float64
 2   NATIONALITY        528884 non-null  str
 3   RESIDENCE          528884 non-null  str
 4   MARITAL_STATUS     410186 non-null  str
 5   CUST_OPENING_DATE  515262 non-null  float64
 6   DATE_OF_BIRTH      427569 non-null  float64
 7   NATURE_CLIENT      528806 non-null  str
 8   BRANCH             528884 non-null  int64
 9   SCORE_KYC          528039 non-null  str
 10  COMPLETED_FILE     289240 non-null  str
 11  LAST_REVIEW_DATE   501479 non-null  float64
 12  NEXT__REVIEW_DATE  504302 non-null  float64
 13  ACCOUNT_STATUS     484444 non-null  str
 14  ACCT_OPENING_DATE  383959 non-null  float64
 15  ACCOUNT_CATEGORY   383959 non-null  float64
 16  ACCOUNT_TYPE_DESC  383959 non-null  str
 17  CURRENCY           383959 non-null  str
 18  ACCT_CLOSE_DATE    221942 non-null  float64
 19  CLOSURE_REASON     143556 non-null  str
 20  ACCT_BALANCE       383959 non-null  float64
 21  INDUSTRY           528884 non-null  int64
 22  SALARY             202235 non-null  float64
 23  PRODUCT_GROUP      320038 non-null  str
 24  PRODUCT_LINE       320038 non-null  str
 25  PRODUCT            320038 non-null  str
 26  ACCOUNTNATURE      383959 non-null  str
 27  STARTDATE          92728 non-null   float64
 28  MATURITYDATE       79551 non-null   float64
 29  AMOUNT             305364 non-null  float64
 30  FIXEDRATE          79549 non-null   float64
 31  PRODUCT_STATUS     92724 non-null   str
 32  PARTYCLASS         528884 non-null  str
 33  LOB                528884 non-null  int64
dtypes: float64(14), int64(4), str(16)
memory usage: 137.2 MB
None

In [48]:
# ==========================================================
# NUMERICAL SUMMARY
# ==========================================================

display(df_data.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CUSTOMER_NO,528884.0,NaN,NaN,NaN,113454259.045195,233515.04459,112872078.0,113252981.0,113425592.0,113687608.25,113871077.0
ACCOUNT_NO,484444.0,NaN,NaN,NaN,2006251547.375499,4916717.052944,2000012480.0,2001674727.25,2003323616.0,2011437681.0,2012605084.0
NATIONALITY,528884,141,TN,509825,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RESIDENCE,528884,137,TN,494837,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MARITAL_STATUS,410186,4,M,219233,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CUST_OPENING_DATE,515262.0,NaN,NaN,NaN,20136149.345842,68027.290249,19960122.0,20070824.0,20140925.0,20191108.0,20260219.0
DATE_OF_BIRTH,427569.0,NaN,NaN,NaN,19763149.662576,172923.402384,11900404.0,19641013.0,19771029.0,19890124.0,20260114.0
NATURE_CLIENT,528806,9,PPH,374969,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRANCH,528884.0,NaN,NaN,NaN,5870.834364,104.791536,1.0,5827.0,5845.0,5883.0,6863.0
SCORE_KYC,528039,5,LR,342718,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COMPLETED_FILE,289240,1,YES,289240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAST_REVIEW_DATE,501479.0,NaN,NaN,NaN,20221483.345366,35431.959896,20040930.0,20200923.0,20230323.0,20250508.0,20260219.0
NEXT__REVIEW_DATE,504302.0,NaN,NaN,NaN,20255637.983611,34841.403625,20060930.0,20240610.0,20261017.0,20280217.0,20301230.0
ACCOUNT_STATUS,484444,2,Active,262502,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACCT_OPENING_DATE,383959.0,NaN,NaN,NaN,20191930.691032,78138.058121,19800101.0,20151209.0,20220720.0,20251029.0,20260219.0
ACCOUNT_CATEGORY,383959.0,NaN,NaN,NaN,4999.703987,2170.514459,1001.0,3045.0,6001.0,6001.0,9005.0
ACCOUNT_TYPE_DESC,383959,149,Comptes Spéciaux d épargne,178236,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CURRENCY,383959,19,TND,357123,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACCT_CLOSE_DATE,221942.0,NaN,NaN,NaN,20241817.876801,13875.951666,20220412.0,20230410.0,20241108.0,20251205.0,20260219.0
CLOSURE_REASON,143556,18,ATB.REASON.13,127174,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACCT_BALANCE,383959.0,NaN,NaN,NaN,4409.008339,810618.483043,-43823115.658,0.0,2.093,1087.9125,64141930.146
INDUSTRY,528884.0,NaN,NaN,NaN,7983.969884,2511.468228,111.0,9000.0,9000.0,9000.0,9998.0
SALARY,202235.0,NaN,NaN,NaN,5588.462902,149836.260474,0.0,400.0,612.0,1647.0,25000000.0
PRODUCT_GROUP,320038,33,ATB.GRP.EPARGNE.ACCT,179237,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRODUCT_LINE,320038,4,ACCOUNTS,225817,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRODUCT,320038,225,ATB.EPARG.ACCT.SPECIAUX,178236,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACCOUNTNATURE,383959,149,Comptes Spéciaux d épargne,178236,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STARTDATE,92728.0,NaN,NaN,NaN,6270448.236207,8375952.754745,1131130.0,1251225.0,1251231.0,20250530.0,20261226.0
MATURITYDATE,79551.0,NaN,NaN,NaN,3980755.431421,6629546.984136,-19000000.0,1260318.0,1261205.0,1341031.0,20310123.0
AMOUNT,305364.0,NaN,NaN,NaN,41297561.350829,442801886.8861,-43823115.658,7.08,1510.68,149000.0,31714285714.0
FIXEDRATE,79549.0,NaN,NaN,NaN,8.654083,2.488274,0.0,8.33,9.33,10.08,13.33
PRODUCT_STATUS,92724,7,CURRENT,62782,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PARTYCLASS,528884,5,Retail,394877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOB,528884.0,NaN,NaN,NaN,6.06235,5.462564,1.0,4.0,4.0,4.0,999.0

In [49]:
# ==========================================================
# DATA QUALITY OVERVIEW
# ==========================================================

quality_summary = pd.DataFrame({

    "Column": df_data.columns,

    "Missing (%)": (
        df_data.isna().mean()*100
    ).round(2),

    "Unique Values":
        df_data.nunique(),

    "Data Type":
        df_data.dtypes.astype(str)

})

display(

    quality_summary.sort_values(

        by="Missing (%)",

        ascending=False

    )

)

                              Column  Missing (%)  Unique Values Data Type
FIXEDRATE                  FIXEDRATE        84.96            722   float64
MATURITYDATE            MATURITYDATE        84.96           4682   float64
PRODUCT_STATUS        PRODUCT_STATUS        82.47              7       str
STARTDATE                  STARTDATE        82.47            722   float64
CLOSURE_REASON        CLOSURE_REASON        72.86             18       str
SALARY                        SALARY        61.76           6011   float64
ACCT_CLOSE_DATE      ACCT_CLOSE_DATE        58.04            646   float64
COMPLETED_FILE        COMPLETED_FILE        45.31              1       str
AMOUNT                        AMOUNT        42.26         178497   float64
PRODUCT                      PRODUCT        39.49            225       str
PRODUCT_LINE            PRODUCT_LINE        39.49              4       str
PRODUCT_GROUP          PRODUCT_GROUP        39.49             33       str
ACCOUNTNATURE          ACCOUNTNATURE        27.40            149       str
ACCT_BALANCE            ACCT_BALANCE        27.40         200311   float64
CURRENCY                    CURRENCY        27.40             19       str
ACCT_OPENING_DATE  ACCT_OPENING_DATE        27.40          10103   float64
ACCOUNT_TYPE_DESC  ACCOUNT_TYPE_DESC        27.40            149       str
ACCOUNT_CATEGORY    ACCOUNT_CATEGORY        27.40            149   float64
MARITAL_STATUS        MARITAL_STATUS        22.44              4       str
DATE_OF_BIRTH          DATE_OF_BIRTH        19.16          32002   float64
ACCOUNT_STATUS        ACCOUNT_STATUS         8.40              2       str
ACCOUNT_NO                ACCOUNT_NO         8.40         410587   float64
LAST_REVIEW_DATE    LAST_REVIEW_DATE         5.18           5006   float64
NEXT__REVIEW_DATE  NEXT__REVIEW_DATE         4.65           6795   float64
CUST_OPENING_DATE  CUST_OPENING_DATE         2.58           5352   float64
SCORE_KYC                  SCORE_KYC         0.16              5       str
NATURE_CLIENT          NATURE_CLIENT         0.01              9       str
CUSTOMER_NO              CUSTOMER_NO         0.00         363569     int64
BRANCH                        BRANCH         0.00            142     int64
RESIDENCE                  RESIDENCE         0.00            137       str
NATIONALITY              NATIONALITY         0.00            141       str
INDUSTRY                    INDUSTRY         0.00            644     int64
PARTYCLASS                PARTYCLASS         0.00              5       str
LOB                              LOB         0.00              9     int64

In [50]:
# ==========================================================
# VARIABLES WITH MORE THAN 30% MISSING
# ==========================================================

high_missing = quality_summary[
    quality_summary["Missing (%)"] > 30
]

display(high_missing)

                          Column  Missing (%)  Unique Values Data Type
COMPLETED_FILE    COMPLETED_FILE        45.31              1       str
ACCT_CLOSE_DATE  ACCT_CLOSE_DATE        58.04            646   float64
CLOSURE_REASON    CLOSURE_REASON        72.86             18       str
SALARY                    SALARY        61.76           6011   float64
PRODUCT_GROUP      PRODUCT_GROUP        39.49             33       str
PRODUCT_LINE        PRODUCT_LINE        39.49              4       str
PRODUCT                  PRODUCT        39.49            225       str
STARTDATE              STARTDATE        82.47            722   float64
MATURITYDATE        MATURITYDATE        84.96           4682   float64
AMOUNT                    AMOUNT        42.26         178497   float64
FIXEDRATE              FIXEDRATE        84.96            722   float64
PRODUCT_STATUS    PRODUCT_STATUS        82.47              7       str

In [51]:
# ==========================================================
# COLUMN CLASSIFICATION
# ==========================================================

business_categories = {

    "Customer Information": [
        "CUSTOMER_NO",
        "NATIONALITY",
        "RESIDENCE",
        "MARITAL_STATUS",
        "DATE_OF_BIRTH",
        "PARTYCLASS",
        "NATURE_CLIENT",
        "SALARY"
    ],

    "Account Information": [
        "ACCOUNT_NO",
        "ACCOUNT_STATUS",
        "ACCOUNT_CATEGORY",
        "ACCOUNT_TYPE_DESC",
        "ACCOUNTNATURE",
        "ACCOUNT_STATUS",
        "ACCT_OPENING_DATE",
        "ACCT_CLOSE_DATE",
        "ACCT_BALANCE",
        "CURRENCY"
    ],

    "Product Information": [
        "PRODUCT_GROUP",
        "PRODUCT_LINE",
        "PRODUCT",
        "PRODUCT_STATUS",
        "AMOUNT",
        "FIXEDRATE",
        "STARTDATE",
        "MATURITYDATE"
    ],

    "Risk & Compliance": [
        "SCORE_KYC",
        "COMPLETED_FILE",
        "LAST_REVIEW_DATE",
        "NEXT__REVIEW_DATE"
    ],

    "Bank Information": [
        "BRANCH",
        "INDUSTRY",
        "LOB"
    ]

}

for category, variables in business_categories.items():

    print("=" * 70)
    print(category)
    print("=" * 70)

    for variable in variables:
        print("•", variable)

======================================================================
Customer Information
======================================================================
• CUSTOMER_NO
• NATIONALITY
• RESIDENCE
• MARITAL_STATUS
• DATE_OF_BIRTH
• PARTYCLASS
• NATURE_CLIENT
• SALARY
======================================================================
Account Information
======================================================================
• ACCOUNT_NO
• ACCOUNT_STATUS
• ACCOUNT_CATEGORY
• ACCOUNT_TYPE_DESC
• ACCOUNTNATURE
• ACCOUNT_STATUS
• ACCT_OPENING_DATE
• ACCT_CLOSE_DATE
• ACCT_BALANCE
• CURRENCY
======================================================================
Product Information
======================================================================
• PRODUCT_GROUP
• PRODUCT_LINE
• PRODUCT
• PRODUCT_STATUS
• AMOUNT
• FIXEDRATE
• STARTDATE
• MATURITYDATE
======================================================================
Risk & Compliance
======================================================================
• SCORE_KYC
• COMPLETED_FILE
• LAST_REVIEW_DATE
• NEXT__REVIEW_DATE
======================================================================
Bank Information
======================================================================
• BRANCH
• INDUSTRY
• LOB